$(document).ready(function(){
    $("#cap").mouseenter(function(){
       $("#capsule").css('display','block');
    });
  $("#cap").mouseleave(function(){
       $("#capsule").css('display','none');
    });
  $("#celm").mouseenter(function(){
       $("#cellm").css('display','block');
    });
  $("#celm").mouseleave(function(){
       $("#cellm").css('display','none');
    });
  $("#celw").mouseenter(function(){
       $("#cellw").css('display','block');
    });
  $("#celw").mouseleave(function(){
       $("#cellw").css('display','none');
    });
  $("#cyt").mouseenter(function(){
       $("#cyto").css('display','block');
    });
  $("#cyt").mouseleave(function(){
       $("#cyto").css('display','none');
    });
  $("#fla").mouseenter(function(){
       $("#flage").css('display','block');
    });
  $("#fla").mouseleave(function(){
       $("#flage").css('display','none');
    });
  $("#incl").mouseenter(function(){
       $("#inc").css('display','block');
    });
  $("#incl").mouseleave(function(){
       $("#inc").css('display','none');
    });
  $("#nucl").mouseenter(function(){
       $("#nuc").css('display','block');
    });
  $("#nucl").mouseleave(function(){
       $("#nuc").css('display','none');
    });
  $("#pil").mouseenter(function(){
       $("#pili").css('display','block');
    });
  $("#pil").mouseleave(function(){
       $("#pili").css('display','none');
    });
  $("#pla").mouseenter(function(){
       $("#plasm").css('display','block');
    });
  $("#pla").mouseleave(function(){
       $("#plasm").css('display','none');
    });
  $("#rib").mouseenter(function(){
       $("#ribo").css('display','block');
    });
  $("#rib").mouseleave(function(){
       $("#ribo").css('display','none');
    });
  $("#bacell").mouseenter(function(){
       $("#bacell").attr({"src":"bacstruc.jpg","width":"900px","height":"700px"});
    });
  $("#bacell").mouseleave(function(){
       $("#bacell").attr({"src":"baccell.gif"});
    });
});